name: Chocolatine
env:
  MIRROR_URL : git@github.com:EpitechPromo2026/B-DOP-200-MAR-2-1-chocolatine-adam.elaoumari.git
  EXECUTABLES : pushswap
on:
  push:
    branches-ignore:
      - 'ga-ignore**'
  pull_request:
    branches-ignore:
      - 'ga-ignore**'

jobs:
    check_repository_cleanliness :
     runs-on: ubuntu-latest
     steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - name: Check for unwanted files
          env:
            VAL: 0
          run: |
             find * | grep -w --line-buffered ".*\.o$" | xargs -I {} echo ::error file={},line=1,col=1,title=Unwanted file detected::{} && echo "VAL=true" >> $GITHUB_ENV
             find * | grep -w --line-buffered ".*\.a$" | xargs -I {} echo ::error file={},line=1,col=1,title=Unwanted file detected::{} && echo "VAL=true" >> $GITHUB_ENV
             find * | grep -w --line-buffered ".*\.so$" | xargs -I {} echo ::error file={},line=1,col=1,title=Unwanted file detected::{} && echo "VAL=true" >> $GITHUB_ENV
             find * | grep -w --line-buffered ".*\.gcno$" | xargs -I {} echo ::error file={},line=1,col=1,title=Unwanted file detected::{} && echo "VAL=true" >> $GITHUB_ENV
             find * | grep -w --line-buffered ".*\.gcda$" | xargs -I {} echo ::error file={},line=1,col=1,title=Unwanted file detected::{} && echo "VAL=true" >> $GITHUB_ENV
             find * | grep -w --line-buffered ".*\.gcov$" | xargs -I {} echo ::error file={},line=1,col=1,title=Unwanted file detected::{} && echo "VAL=true" >> $GITHUB_ENV
             find * | grep -w --line-buffered ".*\~$" | xargs -I {} echo ::error file={},line=1,col=1,title=Unwanted file detected::{} && echo "VAL=true" >> $GITHUB_ENV
             find * | grep -w --line-buffered "#.*\$" | xargs -I {} echo ::error file={},line=1,col=1,title=Unwanted file detected::{} && echo "VAL=true" >> $GITHUB_ENV
             find * | grep -i -w --line-buffered "pain_au_chocolat"  | xargs -I {} echo ::error file={},line=1,col=1,title=Unwanted file detected::{} && echo "VAL=true" >> $GITHUB_ENV
             find * | grep -i -w --line-buffered "tmp"  | xargs -I {} echo ::error file={},line=1,col=1,title=Unwanted file detected::{} && echo "VAL=true" >> $GITHUB_ENV
        - name: Check for result
          if:  ${{ VAL == 'true' }}
          run: exit 1
          continue-on-error: false
