name: Chocolatine
env:
  MIRROR_URL : git@github.com:EpitechPromo2026/B-DOP-200-MAR-2-1-chocolatine-adam.elaoumari.git
  EXECUTABLES : pushswap
on:
  push:
    branches-ignore:
      - 'ga-ignore**'
  pull_request:
    branches-ignore:
      - 'ga-ignore**'

jobs:
    check_repository_cleanliness :
     runs-on: ubuntu-latest
     steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - name: Check for unwanted files
          run: |
             find * -name "#*" -exec echo ::error file={},line=1,col=1,title=Unwanted file detected::{} \;
             find * -name "*#" -exec echo ::error file={},line=1,col=1,title=Unwanted file detected::{} \;
             find * -name "*~" -exec echo ::error file={},line=1,col=1,title=Unwanted file detected::{} \;
             find * -name "*.o" -exec echo ::error file={},line=1,col=1,title=Unwanted file detected::{} \;
             find * -name "*.a" -exec echo ::error file={},line=1,col=1,title=Unwanted file detected::{} \;
             find * -name "*.so" -exec echo ::error file={},line=1,col=1,title=Unwanted file detected::{} \;
             find * -name "*.gcno" -exec echo ::error file={},line=1,col=1,title=Unwanted file detected::{} \;
             find * -name "*.gcda" -exec echo ::error file={},line=1,col=1,title=Unwanted file detected::{} \;
             find * -name "*.gcov" -exec echo ::error file={},line=1,col=1,title=Unwanted file detected::{} \;
             find * -name "pain_au_chocolat" -exec echo ::error file={},line=1,col=1,title=Unwanted file detected::{} \;
             find tmp/ -name -type f "*" -exec echo ::error file={},line=1,col=1,title=Unwanted file detected::{} \;
             o=$(find * -name "*.o" -exec echo ::error file={},line=1,col=1,title=Unwanted file detected::{} \;)
